# Generated by Django 2.1.7 on 2019-03-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayooluwaoyewoscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayooluwaoyewoscrumy.ScrumyUser'),
        ),
    ]
